### ISSUE TITLE
Remarkable fail to lauch on openSUSE

### ISSUE THREAD

**Issue by noraj** [remarkableapp/Remarkable-Linux#24]
Remarkable fail to lauch on openSUSE Leap 42.1

```
remarkable
*Spellchecking not enabled.
*To enable spellchecking install pygtkspellcheck
*https://pypi.python.org/pypi/pygtkspellcheck/
/usr/lib/python3/dist-packages/remarkable_lib/Builder.py:86: Warning: The property GtkWidget:margin-left is deprecated and shouldn't be used anymore. It will be removed in a future version.
  Gtk.Builder.add_from_file(self, filename)
/usr/lib/python3/dist-packages/remarkable_lib/Builder.py:86: Warning: The property GtkWidget:margin-right is deprecated and shouldn't be used anymore. It will be removed in a future version.
  Gtk.Builder.add_from_file(self, filename)

(remarkable:13918): Gtk-WARNING **: No object called: 
openjdk version "1.8.0_72"
OpenJDK Runtime Environment (build 1.8.0_72-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 1329, in update_live_preview
    html_middle = markdown.markdown(text, self.default_extensions)
AttributeError: 'module' object has no attribute 'markdown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 1332, in update_live_preview
    html_middle = markdown.markdown(text, extensions =self.safe_extensions)
AttributeError: 'module' object has no attribute 'markdown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/X11/remarkable", line 66, in <module>
    remarkable.main()
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 48, in main
    window = RemarkableWindow.RemarkableWindow()
  File "/usr/lib/python3/dist-packages/remarkable_lib/Window.py", line 54, in __new__
    new_object.finish_initializing(builder)
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 143, in finish_initializing
    self.update_live_preview(self)
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 1334, in update_live_preview
    html_middle = markdown.markdown(text)
AttributeError: 'module' object has no attribute 'markdown'
```

**Comment by huanghaikai** [comment]
I got this problem in opensuse leap42.1,too.  I had already installed python3-markdown lib, but still didn't work

**Comment by remarkableapp** [comment]
V1.75 has since been released, please check if the error still exists.
The repository is now [located here](https://github.com/jamiemcg/Remarkable).

**Comment by huanghaikai** [comment]
version 1.75 still doesn't work in opensuse 42.1 !!!! I have download github repository and .rpm ,both of them work failed.

Error code:

Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/**init**.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 26, in <module>
    gi.require_version("WebKit", '3.0')
  File "/usr/lib64/python3.4/site-packages/gi/**init**.py", line 100, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available

**Comment by maresmar** [comment]
You have to install `libwebkitgtk3-devel` too, than it works fine. So all you have to do is install Remarkable's rpm and theses libraries:
`sudo zypper in libwebkitgtk3-devel python3-Markdown`

**Comment by chrisstafford** [comment]
I know this issue is rather old, but I was able to fix this by editing the RPM and adding the required dependencies, here's a quick rundown.
```
sudo zypper install rpmrebuild
rpmrebuild -e -p remarkable-1.87-1.rpm
```

change the line 
`Requires:	python3-markdown` to 
`Requires:	python3-Markdown`

Add the following lines
`Requires: libwebkitgtk3-devel`
`Requires: typelib-1_0-GtkSource-3_0`
Write the file

Install wkhtmltopdf for your version of openSUSE from here: https://software.opensuse.org/package/wkhtmltopdf

Install the newly built rpm

```
sudo zypper in ~/rpmbuild/RPMS/noarch/remarkable-1.87-1.noarch.rpm 
```

**Comment by maresmar** [comment]
Lasted Tumbleweed snapshot doesn't contain `libwebkitgtk3-devel`, the one-click install from https://software.opensuse.org/package/libwebkitgtk3-devel solves it for me (there are many dependencies). Hopefully, they return the package back someday.

**Comment by omushpapa** [comment]
Thanks to @chrisstafford and @mmrmartin. I integrated both of their solutions and finally got the rpm to work on OpenSUSE 42.3. That is, despite using the unstable package of wkhtmltopdf from the OpenSUSE repos.

**Comment by taw00** [comment]
Doesn't work for Fedora 27.

`ValueError: Namespace WebKit not available` on Fedora 27 after installing using DNF. There is no available GTK3 version of WebKit libraries. Moving on to another notetaking application, I suppose.

**Comment by H4medRostami** [comment]
doesn't work on F28 
get "ValueError: Namespace WebKit not available " error.

**Comment by fperal** [comment]
the same problem arise in Leap 15.2
